### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by andszk** [yuandong-tian/scheduler#1]
after running ./schedule_plan.sh sample_todo.org
-------- Not done list --------

-------------------------------
Traceback (most recent call last):
  File "./schedule.py", line 14, in <module>
    import schedule_pylib
ImportError: /home/leto/repos/scheduler/schedule_pylib.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE

there appear to be some problem in linking. Also missing #include<algorithm> in schedule_lib.cc.

I understand well that this project is long dead, but it was exactly what I was looking for, therefore I would appreciate greatly if you could help me on this issue, or direct me to some kind of software that can do scheduling in such manner.

**Comment by yuandong-tian** [comment]
Thank you for your interest! The project is now in https://github.com/yuandong-tian/scheduler_new. Less dependency and easier to use. Enjoy!
